export const allProviders = [
  {
    id: "1",
    name: "Fakhar Rashid",
    profession: "Electrician",
    rating: 4.9,
    reviews: 124,
    image: "/placeholder2.png",
    location: "Lahore",
    verified: true,
    experience: 8,
    completedJobs: 215,
    services: [{ duration: 90, price: 3500 }],
    skills: ["Wiring", "Installation", "Repairs", "Maintenance"],
  },
  {
    id: "2",
    name: "Abdullah Malik",
    profession: "Interior Designer",
    rating: 4.8,
    reviews: 98,
    image: "/placeholder2.png",
    location: "Karachi",
    verified: true,
    experience: 6,
    completedJobs: 178,
    services: [{ duration: 120, price: 2500 }],
    skills: ["Space Planning", "Color Scheme", "Furniture", "Lighting"],
  },
  {
    id: "3",
    name: "Ali Ahmad",
    profession: "Plumber",
    rating: 4.7,
    reviews: 156,
    image: "/placeholder2.png",
    location: "Islamabad",
    verified: true,
    experience: 10,
    completedJobs: 342,
    services: [{ duration: 60, price: 2000 }],
    skills: ["Leak Repair", "Installation", "Drain Cleaning"],
  },
  {
    id: "4",
    name: "Abdul Ahad",
    profession: "Interior Designer",
    rating: 4.8,
    reviews: 98,
    image: "/placeholder2.png",
    location: "Karachi",
    verified: true,
    experience: 6,
    completedJobs: 178,
    services: [{ duration: 120, price: 2500 }],
    skills: ["Space Planning", "Color Scheme", "Furniture", "Lighting"],
  },
];
